# -*- coding: utf-8 -*-
"""globalobject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_7hA9-WpKiDUZ8J23PS2RflXZsVKj70M
"""

from google.colab import drive
drive.mount('/content/drive')

seq_length = 5 # length of sequence for a training example
epoch = 30
MAXLEN = 43
DENSE_HIDDEN_SIZE = 20
train_model_percentage = 90

multiple_delta_number = 5
ADDRESS_PREDICT_SIZE = 1001
EMBEDDING_DIM = 64
RNN_UNITS = 1024

BUFFER_SIZE = 10000

text_file = '473.astar-s0'

